project:
  type: website

website:
  title: "R4DSA_tidymodels"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Hands-on Exercise 1
        href: TM_Hands-on_Ex1\\TM_Hands-on_Ex1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

